# Site settings
title: EdgarC
email: edaniel15@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bienvenido a mi blog personal!, aqui encontraras varios scripts
  que me sirven a diario, algunas investigaciones, herramientas, gist, plugins
  etc, publicando desde Lima - Peru
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://edux87.github.io" # the base hostname & protocol for your site
twitter_username: edaniel15
github_username:  Edux87

# Build settings
markdown: kramdown
